[project]
name = "aceai"
version = "0.1.2"
description = "AI agent framework that delivers"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ididi>=1.7.9",
    "litellm>=1.80.7",
    "msgspec>=0.20.0",
]
authors = [
    {name = "raceychan", email = "raceychan@gmail.com"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/aceai"]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
